### ISSUE TITLE
Tidak ada Tutorial pull request ke repo ?

### ISSUE THREAD

**Issue by sofiull** [ikanbakarenak/hari-pertama#3]
Tolong sediakan tutorial cara pull request ke repo untuk memudahkan contributor

**Comment by ikanbakarenak** [comment]
Terima kasih atas sarannya. Tutorial sudah ditambahkan kedalam README.md dalam bentuk gif agar mudah dipelajari. Untuk file gif nya bisa diunduh di folder "Asset" pada repository **hari-pertama**. Terimakasih :)
